version: '3'

services:
  db:
    image: mongo
#    ports:
#      - "27017:27017"
    expose:
      - "27017"
  redis:
    image: redis
    command: redis-server
#    ports:
#      - "6379:6379"
    expose:
      - "6379"
  master:
    build: .
#    command: "python -c \"while True: pass\""
    entrypoint: "start_master.sh"
#    env_file:
#      - default.env
    volumes:
      - ./apicrawler
      - ./apicrawler_slave
#    ports:
#      - "8000:8000"
    depends_on:
      - db
      - redis