version: '3'

services:
  mongos1:
    image: mongo
    ports:
      - "27017:27017"
#    expose:
#      - "27017"
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf --protected-mode no
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  master:
    image: yuance/apicrawler:latest
#    command: "python -c \"while True: pass\""
    entrypoint: "start_master.sh"
    volumes:
      - "./apicrawler:/App/apicrawler"
      - "./scripts:/App/apicrawler/scripts"
#      - "./start_master.sh:/App/start_master.sh"
      - "./settings.py:/App/apicrawler/apicrawler/settings.py"
    depends_on:
      - mongos1
      - redis

  slave1:
    image: yuance/apicrawler:latest
    entrypoint: "start_slave1.sh"
    volumes:
      - "./apicrawler:/App/apicrawler"
      - "./scripts:/App/apicrawler/scripts"
#      - "./start_slave1.sh:/App/start_slave1.sh"
      - "./settings.py:/App/apicrawler/apicrawler/settings.py"
    depends_on:
      - mongos1
      - redis
      - master
#
#  slave2:
#    image: yuance/apicrawler:latest
#    entrypoint: "start_slave1.sh"
#    volumes:
#      - "./apicrawler:/App/apicrawler"
#      - "./scripts:/App/apicrawler/scripts"
#      - "./settings.py:/App/apicrawler/apicrawler/settings.py"
#
#    depends_on:
#      - mongos1
#      - redis
#      - master