version: "3.3"

networks:
  net:
    driver: bridge

services:

  data1:
    image: mongo:3.4
    container_name: data1
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  data2:
    image: mongo:3.4
    container_name: data2
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  data3:
    image: mongo:3.4
    container_name: data3
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  cfg1:
    image: mongo:3.4
    depends_on:
      - data1
      - data2
      - data3
    container_name: cfg1
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  cfg2:
    image: mongo:3.4
    depends_on:
    - data1
    - data2
    - data3
    container_name: cfg2
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  cfg3:
    image: mongo:3.4
    depends_on:
    - data1
    - data2
    - data3
    container_name: cfg3
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    expose:
      - 27017
    networks:
      - net

  mongos1:
    image: mongo:3.4
    depends_on:
      - cfg1
      - cfg2
      - cfg3
    container_name: mongos1
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    expose:
      - 27017
    networks:
      - net

  mongos2:
    image: mongo:3.4
    depends_on:
      - cfg1
      - cfg2
      - cfg3
    container_name: mongos2
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    expose:
      - 27017
    networks:
      - net

  bootstrap:
    image: stefanprodan/mongo-bootstrap:latest
    depends_on:
      - mongos1
      - mongos2
    container_name: mongo-bootstrap
    command:
      - '-dataSet=datars/data1:27017,data2:27017,data3:27017'
      - '-configSet=cfgrs/cfg1:27017,cfg2:27017,cfg3:27017'
      - '-mongos=mongos1:27017,mongos2:27017'
    networks:
      - net

  redis:
    image: redis
    command: redis-server
    networks:
      - net
#    ports:
#      - "6379:6379"

  master:
    image: yuance/apicrawler:latest
#    command: "python -c \"while True: pass\""
    entrypoint: "start_master.sh"
    networks:
      - net
    volumes:
      - "./apicrawler:/App/apicrawler"
      - "./scripts:/App/apicrawler/scripts"
#      - "./start_master.sh:/App/start_master.sh"
      - "./settings.py:/App/apicrawler/apicrawler/settings.py"
    depends_on:
      - bootstrap
      - redis

  slave1:
    image: yuance/apicrawler:latest
    entrypoint: "start_slave1.sh"
    networks:
      - net
    volumes:
      - "./apicrawler:/App/apicrawler"
      - "./scripts:/App/apicrawler/scripts"
#      - "./start_master.sh:/App/start_master.sh"
      - "./settings.py:/App/apicrawler/apicrawler/settings.py"

    depends_on:
      - redis
      - master

  slave2:
    image: yuance/apicrawler:latest
    entrypoint: "start_slave1.sh"
    networks:
      - net
    volumes:
      - "./apicrawler:/App/apicrawler"
      - "./scripts:/App/apicrawler/scripts"
#      - "./start_master.sh:/App/start_master.sh"
      - "./settings.py:/App/apicrawler/apicrawler/settings.py"

    depends_on:
      - redis
      - master

  slave3:
    image: yuance/apicrawler:latest
    entrypoint: "start_slave1.sh"
    networks:
      - net
    volumes:
      - "./apicrawler:/App/apicrawler"
      - "./scripts:/App/apicrawler/scripts"
#      - "./start_master.sh:/App/start_master.sh"
      - "./settings.py:/App/apicrawler/apicrawler/settings.py"

    depends_on:
      - redis
      - master
